22-django/ProyectoDjango/ProyectoDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('pages.urls')),
    path('', include('blog.urls')),
]

#Ruta imagenes
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

22-django/ProyectoDjango/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('articulos/', views.list, name="list"),
    path('categoria/<int:category_id>', views.category, name="category"),
    path('articulo/<int:article_id>', views.article, name="article")
]

22-django/ProyectoDjango/mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('inicio/', views.index, name="inicio"),
    path('registro/', views.register_page, name="register"),
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout")
]

22-django/ProyectoDjango/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pagina/<str:slug>', views.page, name="page")
]

22-django/ProyectoDjango/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')
    description = models.CharField(max_length=255, verbose_name='Descripción')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creado el')

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=150, verbose_name='Título')
    content = RichTextField(verbose_name='Contenido')
    image = models.ImageField(default='null', verbose_name="Imagen", upload_to="articles")
    public = models.BooleanField(verbose_name='¿Publicado?')
    user = models.ForeignKey(User, editable=False, verbose_name='Usuario', on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, verbose_name='Categorías', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creado el')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Editado el')

    class Meta:
        verbose_name = 'Artículo'
        verbose_name_plural = 'Artículos'
        ordering = ['-created_at']

    def __str__(self):
        return self.title

22-django/ProyectoDjango/mainapp/models.py
from django.db import models

# Create your models here.

22-django/ProyectoDjango/pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=50, verbose_name="Título")
    content = RichTextField(verbose_name="Contenido")
    slug = models.CharField(unique=True, max_length=150, verbose_name="URL amigable")
    order = models.IntegerField(default=0, verbose_name="Orden")
    visible = models.BooleanField(verbose_name="¿Visible?")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Actualizado el")

    class Meta:
        verbose_name = "Página"
        verbose_name_plural = "Páginas"

    def __str__(self):
        return self.title
    

22-django/ProyectoDjango/mainapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

22-django/ProyectoDjango/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from blog.models import Category, Article
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url="login")
def list(request):

    # Sacar artículos
    articles = Article.objects.all()

    # Paginar artículos
    paginator = Paginator(articles, 2)

    # Recoger numero pagina
    page = request.GET.get('page')
    page_articles = paginator.get_page(page)

    return render(request, 'articles/list.html', {
        'title': 'Artículos',
        'articles': page_articles
    })

@login_required(login_url="login")
def category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    # articles = Article.objects.filter(categories=category_id)

    return render(request, 'categories/category.html', {
        'category': category
    })

@login_required(login_url="login")
def article(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    return render(request, 'articles/detail.html', {
        'article': article
    })

22-django/ProyectoDjango/mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from mainapp.forms import RegisterForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):

    return render(request, 'mainapp/index.html', {
        'title': 'Inicio'
    })

def about(request):

    return render(request, 'mainapp/about.html', {
        'title': 'Sobre nosotros'
    })

def register_page(request):

    if request.user.is_authenticated:
        return redirect("inicio")
    else:

        register_form = RegisterForm()

        if request.method == 'POST':
            register_form = RegisterForm(request.POST)
            if register_form.is_valid():
                register_form.save()
                messages.success(request, "Te has registrado correctamente")

                return redirect('/inicio')

        return render(request, 'users/register.html', {
            'title': 'Registro',
            'register_form': register_form
        })

def login_page(request):
    if request.user.is_authenticated:
        return redirect("inicio")
    else:

        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('inicio')
            else:
                messages.warning(request, "No te has identificado correctamente")

        return render(request, 'users/login.html', {
            'title': 'Identificate'
        })

def logout_user(request):
    logout(request)
    return redirect('login')

22-django/ProyectoDjango/pages/views.py
from django.shortcuts import render
from .models import Page
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url="login")
def page(request, slug):

    page = Page.objects.get(slug=slug)

    return render(request, "pages/page.html", {
        "page": page
    })

22-django/ProyectoDjango/blog/templates/articles/articles.html
{% for article in articles %}
        <article class="article-item">
            {% if article.image != 'null' and article.image.url|length >= 1 %}
                <div class="image">
                    <img src="{{article.image.url}}"/>
                </div>
            {% endif %}

            <div class="data">
                <h2>
                    <a href="{% url 'article' article.id %}">
                    {{article.title}}
                    </a>
                </h2>
                <p>
                    {% for category in article.categories.all %}
                        <a href="{% url 'category' category.id %}">{{category.name}}</a>
                        {% if forloop.counter < article.categories.all|length %}
                            {{'-'}}
                        {% endif %}
                    {% endfor %}
                </p>
                <span class="date">
                {{article.user.first_name}} {{article.user.last_name}}
                {{article.user.email}}
                |
                {{article.created_at}}
                </span>
                
                <p>
                    {{article.content|safe}}
                </p>
            </div>

            <div class="clearfix"></div>
        </article>
           
{% endfor %}

22-django/ProyectoDjango/blog/templates/articles/detail.html
{% extends 'layouts/layout.html' %}

{% block title %} {{article.title}} {% endblock %}

{% block content %}

        {% if article.image != 'null' and article.image.url|length >= 1 %}
            <div class="image">
                <img src="{{article.image.url}}"/>
            </div>
        {% endif %}

    <h1 class="title">{{article.title}}</h1>
    <span class="date">{{article.created_at}}</span>
    <p class="content">
        {{article.content|safe}}
    </p>
{% endblock %}

22-django/ProyectoDjango/blog/templates/articles/list.html
{% extends 'layouts/layout.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1 class="title">{{title}}</h1>
   
    {% include 'articles/articles.html' %}
    {% include 'articles/pagination.html' %}

{% endblock %}

22-django/ProyectoDjango/blog/templates/articles/pagination.html
<div class="pagination">
    {% if articles.has_previous %}
        <a href="?page=1">&laquo; Primero</a>
        <a href="?page={{ articles.previous_page_namber }}">
            Anterior
        </a>
    {% endif %}

    <span class="actual">
        Página {{articles.namber}} de {{articles.paginator.num_pages}}
    </span> 
    {% if articles.has_next %}
        
        <a href="?page={{ articles.next_page_namber }}">
            Siguiente
        </a>
        <a href="?page={{articles.paginator.num_pages}}">Última &raquo;</a>
    {% endif %}
</div>

22-django/ProyectoDjango/blog/templates/categories/category.html
{% extends 'layouts/layout.html' %}

{% block title %} {{category.name}} {% endblock %}

{% block content %}
    <h1 class="title">{{category.name}}</h1>
    <p>{{category.description}}</p>
   
    {% include  'articles/articles.html' with articles=category.article_set.all %}

{% endblock %}

22-django/ProyectoDjango/mainapp/templates/layouts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
        
        {% endblock %}
        | Flavio Scheck
    </title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>

<body>

    <!--cabecera de la página-->
    <header>
        <div id="logotipo">
            <!--logo django-->
            <img src="{% static 'images/logo.png' %}" />
            <h1>Proyecto con Django</h1>
        </div>
        
    </header>

    <nav>
        <ul>
            <li>
                <a href="{% url 'index' %}">Inicio</a>
            </li>
            {% if user.email %}
                <li>
                    <a href="{% url 'list' %}">Categorías</a>
                    <ul>
                        {% for category in categories %}
                            <li>
                                <a href="{% url 'category' category.0 %}">{{category.1}}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% for page in pages %}
                    <li>
                        <a href="{% url 'page' page.2 %}">{{page.1}}</a>
                    </li>
                {% endfor %}
                <li>
                    <a href="{% url 'logout' %}">Cerrar sesión</a>
                </li>

            {% else %}
                <li>
                    <a href="{% url 'register' %}">Registro</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </nav>

    <div class= "barra">
        <span class="esquina-izquierda"></span>
        <span class="relleno-barra"></span>
        <span class="esquina-derecha"></span>
    </div>

    <div id="content">
        <div class="box">
            {% block content %}
                <!--Codigo que viene de templates-->
                <strong>Contenido del bloque original!!</strong>
            {% endblock %}
        </div>
    </div>
  
    <footer>
        Master en Python &copy; Flavio Scheck WEB - {% now "d/m/y" %}
    </footer>

</body>

</html>

22-django/ProyectoDjango/mainapp/templates/mainapp/about.html
{% extends 'layouts/layout.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1>{{title}}</h1>
{% endblock %}

22-django/ProyectoDjango/mainapp/templates/mainapp/index.html
{% extends 'layouts/layout.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1>{{title}}</h1>
    <hr/>
    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                {{message}}
        {% endfor %}
    {% endif %}

    {% if user.email %}
        <h2>Bienvenido, {{request.user.first_name}} {{user.last_name}}</h2>
        <p>
            {{user.email}}
        </p>
    
    {% else %}
        <h2>Identificate para ver más</h2>
    {% endif %}

{% endblock %}

22-django/ProyectoDjango/mainapp/templates/users/login.html
{% extends 'layouts/layout.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1>{{title}}</h1>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning">
                {{message}}
        {% endfor %}
    {% endif %}

    <form method="post" action="">
        {% csrf_token %}

        <label for="username">Nombre de usuario</label>
        <input type="text" name="username" />

        <label for="password">Contraseña</label>
        <input type="password" name="password" />

        <input type="submit" value="Login" />
    </form>

{% endblock %}

22-django/ProyectoDjango/mainapp/templates/users/register.html
{% extends 'layouts/layout.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1>{{title}}</h1>

    {{register_form.errors}}

    <form method="post" action="">
        {% csrf_token %}

        {% comment %}
        {{register_form.as_p}}
        {% endcomment %}
        
        {% for field in register_form %}
            <label>{{field.label}}</label>
            {{field}}
        {% endfor %}
        <input type="submit" value="Registrarse" />
    </form>

{% endblock %}

22-django/ProyectoDjango/pages/templates/pages/page.html
{% extends 'layouts/layout.html' %}

{% block title %} {{page.title}} {% endblock %}

{% block content %}
    <h1 class="title">{{page.title}}</h1>
    <span class="date">{{page.created_at}}</span>
    <p class="content">
        {{page.content|safe}}
    </p>
{% endblock %}